/**
 * gpsext
 * Get GPS position filtered by datas from gyros, accel and magnetometers
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <netdb.h>
#include <fcntl.h>
#include <math.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/socket.h>

#include <json-c/json.h>

#include <systemd/sd-event.h>

#include <afb/afb-binding.h>
#include <afb/afb-service-itf.h>

#include "../models/accelerometer_datas.h"
#include "../models/error.h"
#include "../models/gps_datas.h"
#include "../models/gyroscope_datas.h"
#include "../models/magnetometer_datas.h"

/* Some useful math values
 * RAD_TO_DEG = 180 / pi 
 */
#define RAD_TO_DEG 57.295779513
#define M_PI  3.14159265358979323846

#define IMU_DEV "/dev/input/event"
#define IMU_ACC 0
#define IMU_MAG 1
#define IMU_GYR 2

#define NB_AXIS 3

struct accelerometer_datas {
	int x;
	int y;
	int z;
};

/*
 * the interface to afb-daemon
 */
const struct afb_binding_interface *afbitf;

/***************************************************************************************/
/***************************************************************************************/
/**                                                                                   **/
/**                                                                                   **/
/**       SECTION: HANDLE IMU DEVICE                                                  **/
/**                                                                                   **/
/**                                                                                   **/
/***************************************************************************************/
/***************************************************************************************/

/*
 * @brief Open IMU event device and return file handler
 * 
 * IMU event device are :
 * 	0 : Accelerometer
 *  1 : Magnetometer
 *  2 : gyroscop
 * 
 * @param integer imu_device: indice of imu event device like described above.
 * 
 * @return int fd : file handler of opened device.
 * 
 */

static int open_dev(int imu_device)
{
    char *fname_path[64];
    int fd;

	/* get dev full path */
	snprintf(*fname_path, sizeof(*fname_path), "%s%d", IMU_DEV, imu_device);
	
	if ((fd = open(*fname_path, O_RDONLY)) < 0) {
	    perror("evdev open");
	    exit(1);
	}

    return fd;
}

/***************************************************************************************/
/***************************************************************************************/
/**                                                                                   **/
/**                                                                                   **/
/**       SECTION: BINDING VERBS IMPLEMENTATION                                       **/
/**                                                                                   **/
/**                                                                                   **/
/***************************************************************************************/
/***************************************************************************************/
/*!
 * @brief Get every datas from the accelerometer.
 */
static accelerometer_datas get_accelerometer()
{
    int i;
	struct accelerometer_datas AccelRaw;
	int *access = (int*)&AccelRaw;
	struct input_absinfo acc_absinfo;

    // Limit scan to X, Y and Z axis as Accel only use those one.
    for (i = 0; i < ACC_AXIS; i++)
    {
        if (ioctl(fd, EVIOCGABS(i), &absinfo) < 0)
        {
            perror("IOCTL : EVIOVGABS error");
        }
        access[i] = absinfo.value;
    }
	
	return AccelRaw;
}

static void verb_get_accelerometer(struct afb_req req)
{
	accelerometer_datas value = get_accelerometer();
	json_object* json = accelerometer_datas_to_json(&value);
	afb_req_success(req, json, NULL);
	json_object_put(json);
}

/*!
 * @brief Get every datas from the GPS.
 */
static gps_datas get_gps()
{
	// TODO: Implement your logic here.
}

static void verb_get_gps(struct afb_req req)
{
	gps_datas value = get_gps();
	json_object* json = gps_datas_to_json(&value);
	afb_req_success(req, json, NULL);
	json_object_put(json);
}

/*!
 * @brief Get every datas from the gyroscope.
 */
static gyroscope_datas get_gyroscope()
{
	// TODO: Implement your logic here.
}

static void verb_get_gyroscope(struct afb_req req)
{
	gyroscope_datas value = get_gyroscope();
	json_object* json = gyroscope_datas_to_json(&value);
	afb_req_success(req, json, NULL);
	json_object_put(json);
}

/*!
 * @brief Get every datas from the magnetometer.
 */
static magnetometer_datas get_magnetometer()
{
	// TODO: Implement your logic here.
}

static void verb_get_magnetometer(struct afb_req req)
{
	magnetometer_datas value = get_magnetometer();
	json_object* json = magnetometer_datas_to_json(&value);
	afb_req_success(req, json, NULL);
	json_object_put(json);
}


/*
 * array of the verbs exported to afb-daemon
 */
static const struct afb_verb_desc_v1 binding_verbs[] = {
  /* VERB'S NAME            SESSION MANAGEMENT          FUNCTION TO CALL         SHORT DESCRIPTION */
  { .name= "get_accelerometer", .session=AFB_SESSION_NONE, .callback=verb_get_accelerometer, .info="Get every datas from the accelerometer."},
  { .name= "get_gps", .session=AFB_SESSION_NONE, .callback=verb_get_gps, .info="Get every datas from the GPS."},
  { .name= "get_gyroscope", .session=AFB_SESSION_NONE, .callback=verb_get_gyroscope, .info="Get every datas from the gyroscope."},
  { .name= "get_magnetometer", .session=AFB_SESSION_NONE, .callback=verb_get_magnetometer, .info="Get every datas from the magnetometer."},
  { .name= NULL } /* marker for end of the array */
};

/*
 * description of the binding for afb-daemon
 */
static const struct afb_binding binding_description =
{
  /* description conforms to VERSION 1 */
  .type= AFB_BINDING_VERSION_1,
  .v1= {			/* fills the v1 field of the union when AFB_BINDING_VERSION_1 */
    .prefix= "gps",		/* the API name (or binding name or prefix) */
    .info= "Get GPS position filtered by datas from gyros, accel and magnetometers",	/* short description of of the binding */
    .verbs = binding_verbs	/* the array describing the verbs of the API */
  }
};

/*
 * activation function for registering the binding called by afb-daemon
 */
const struct afb_binding *afbBindingV1Register(const struct afb_binding_interface *itf)
{
	afbitf = itf;			/* records the interface for accessing afb-daemon */
	return &binding_description;	/* returns the description of the binding */
}

int afbBindingV1ServiceInit(struct afb_service service)
{
	return connection();
}
