/**
 * gpsext
 * Get GPS position filtered by datas from gyros, accel and magnetometers
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "accelerometer_datas.h"

json_object* gpsext_accelerometer_datas_to_json(gpsext_accelerometer_datas* s)
{
	json_object* o = json_object_new_object();
	json_object* o_axis_x = json_object_new_double(s->axis_x);
	json_object_object_add(o, "axis_x", o_axis_x);
	json_object* o_axis_y = json_object_new_double(s->axis_y);
	json_object_object_add(o, "axis_y", o_axis_y);
	json_object* o_axis_z = json_object_new_double(s->axis_z);
	json_object_object_add(o, "axis_z", o_axis_z);
    return o;
}

gpsext_accelerometer_datas json_to_gpsext_accelerometer_datas(json_object* s)
{
	// TODO: Implement your logic here.
}

void free_gpsext_accelerometer_datas_members(gpsext_accelerometer_datas* s)
{
	// TODO: Implement your logic here.
}

