/**
 * gpsext
 * Get GPS position filtered by datas from gyros, accel and magnetometers
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#ifndef _AFB_DAEMON_BINDING_gpsext_error_H_
#define _AFB_DAEMON_BINDING_gpsext_error_H_

#include <json-c/json.h>

/*! @brief 
 */
typedef struct gpsext_error_tag
{
	int code;
	char* message;
	char* fields;
} gpsext_error;

/*!
 * @brief Build a json object from a gpsext_error.
 * @param[in] s gpsext_error from which the json object is built.
 * @return A json object corresponding to the gpsext_error object.
 */
json_object* gpsext_error_to_json(gpsext_error* s);

/*!
 * @brief Build a gpsext_error object from json object.
 * @param[in] o The json object from which the gpsext_error is built.
 * @return A gpsext_error object corresponding to the json object.
 * @remarks char* members are dynamically allocated. You should use the free_gpsext_error_members function to free these members.
 */
gpsext_error json_to_gpsext_error(json_object* s);

/*!
 * @brief Free dynamically allocated gpsext_error's members such as char*.
 * @param[in] s Object to free members.
 */
void free_gpsext_error_members(gpsext_error s);

#endif /* _AFB_DAEMON_BINDING_gpsext_error_H_ */
