/**
 * gpsext
 * Get GPS position filtered by datas from gyros, accel and magnetometers
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "error.h"

json_object* gpsext_error_to_json(gpsext_error* s)
{
	json_object* o = json_object_new_object();
	json_object* o_code = json_object_new_int(s->code);
	json_object_object_add(o, "code", o_code);
	json_object* o_message = json_object_new_char*(s->message);
	json_object_object_add(o, "message", o_message);
	json_object* o_fields = json_object_new_char*(s->fields);
	json_object_object_add(o, "fields", o_fields);
    return o;
}

gpsext_error json_to_gpsext_error(json_object* s)
{
	// TODO: Implement your logic here.
}

void free_gpsext_error_members(gpsext_error* s)
{
	// TODO: Implement your logic here.
}

