/**
 * gpsext
 * Get GPS position filtered by datas from gyros, accel and magnetometers
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "gps_datas.h"

json_object* gpsext_gps_datas_to_json(gpsext_gps_datas* s)
{
	json_object* o = json_object_new_object();
	json_object* o_longitude = json_object_new_double(s->longitude);
	json_object_object_add(o, "longitude", o_longitude);
	json_object* o_latitude = json_object_new_double(s->latitude);
	json_object_object_add(o, "latitude", o_latitude);
	json_object* o_altitude = json_object_new_double(s->altitude);
	json_object_object_add(o, "altitude", o_altitude);
	json_object* o_speed = json_object_new_double(s->speed);
	json_object_object_add(o, "speed", o_speed);
    return o;
}

gpsext_gps_datas json_to_gpsext_gps_datas(json_object* s)
{
	// TODO: Implement your logic here.
}

void free_gpsext_gps_datas_members(gpsext_gps_datas* s)
{
	// TODO: Implement your logic here.
}

