/**
 * gpsext
 * Get GPS position filtered by datas from gyros, accel and magnetometers
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#ifndef _AFB_DAEMON_BINDING_gpsext_gyroscope_datas_H_
#define _AFB_DAEMON_BINDING_gpsext_gyroscope_datas_H_

#include <json-c/json.h>

/*! @brief 
 */
typedef struct gpsext_gyroscope_datas_tag
{
	int axis_x;
	int axis_y;
	int axis_z;
} gpsext_gyroscope_datas;

/*!
 * @brief Build a json object from a gpsext_gyroscope_datas.
 * @param[in] s gpsext_gyroscope_datas from which the json object is built.
 * @return A json object corresponding to the gpsext_gyroscope_datas object.
 */
json_object* gpsext_gyroscope_datas_to_json(gpsext_gyroscope_datas* s);

/*!
 * @brief Build a gpsext_gyroscope_datas object from json object.
 * @param[in] o The json object from which the gpsext_gyroscope_datas is built.
 * @return A gpsext_gyroscope_datas object corresponding to the json object.
 * @remarks char* members are dynamically allocated. You should use the free_gpsext_gyroscope_datas_members function to free these members.
 */
gpsext_gyroscope_datas json_to_gpsext_gyroscope_datas(json_object* s);

/*!
 * @brief Free dynamically allocated gpsext_gyroscope_datas's members such as char*.
 * @param[in] s Object to free members.
 */
void free_gpsext_gyroscope_datas_members(gpsext_gyroscope_datas s);

#endif /* _AFB_DAEMON_BINDING_gpsext_gyroscope_datas_H_ */
